### PR TITLE
imx8qm: load hdmi firmware before booting

### PR DESCRIPTION
**Pull request by panufi**
Signed-off-by: Panu Finnila <panu.finnila@unikie.com>

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by nesteroff** [comment]
This is great but I'm wondering if you guys think we should push 0001-imx8qm-uefi.patch to our uboot fork (https://github.com/tiiuae/uboot-imx8/tree/lf_v2022.04-uefi)? I guess it would be easier to have our changes for both 8qxp and 8qm in one place.

**Comment by vilvo** [comment]
> This is great but I'm wondering if we you guys think we should push 0001-imx8qm-uefi.patch to our uboot fork (https://github.com/tiiuae/uboot-imx8/tree/lf_v2022.04-uefi)? I guess it would be easier to have our changes for both 8qxp and 8qm in one place

I agree with @nesteroff - better store u-boot-patches there.

**Comment by panufi** [comment]
Please add access into tiiuae/uboot-imx8

**Comment by vilvo** [comment]
> Please add access into tiiuae/uboot-imx8

Done

**Comment by vilvo** [comment]
Moved to uboot at https://github.com/tiiuae/uboot-imx8/commit/c2535837ee018bb6336f7043394072aaadcace34

**Pull request closed without merging**
